### ISSUE TITLE
Add !help <command> for command documentation

### ISSUE THREAD

**Issue by social-assassin** [TeamShellSMM/ShellBot3000#119]
**Describe the solution you'd like**
Example:

> !help add
> !help !add

Output: 
!add [XXX-XXX-XXX] [Level-Name]
As soon as you have the required clearpoints (it depends on your team how much that is) you can submit a level to the moderators with this. You'll get a notification if it's approved, still needs some fixes or if it doesn't fit the team.

**Comment by Liafdev** [comment]
To do that we probably need a new db table "commands" or something, with the help string, format, etc...
Would also be nice to change the features page on makerteams to be dynamic then, we'll probably need categories as well in the db for that.
