### ISSUE TITLE
add optional message function to !tsfixapprove and !tsfixreject

### ISSUE THREAD

**Issue by zajd** [TeamShellSMM/ShellBot3000#45]
add those messages to the approval embed (or before it) as well

**Comment by a-unique-id** [comment]
I think this was already implemented at least for !tsreject.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/45527149/82161487-bd4fd780-98cf-11ea-9015-84c1b4d2fa6d.png">

!tsapproves just updates your vote and approves it like normal, but maybe we can make it appear with a special message too to highlight the newest vote, now that i think about it

**Comment by Liafdev** [comment]
Should work now in #60

**Comment by zajd** [comment]
Sounds good!
