### ISSUE TITLE
Add !help commands

### ISSUE THREAD

**Issue by social-assassin** [TeamShellSMM/ShellBot3000#48]

**Comment by a-unique-id** [comment]
Currently there's a `!command` and `!help` command just points to the website which shows all the commands. 

I was wondering if we could also somehow do `!help command` or `!help search` and it might surface relevant instructions or commands that could help them.

I'm not really sure about it. One time i contemplated adding help strings, and the default messages in the commands/command.js files. But i decided to put the messages in one file so we have it one place.

If we can have the commands, descriptions keywords and stuff as maybe like default strings, we can probably automatically document the commands and stuff and could even plausibly update the features page in the website

**Comment by a-unique-id** [comment]
I'll change the scope of this command to just show just the first steps someone could do. I'll possibly add a language option to. example:
```
!help
- To do anything, you will have to register first by using !register in the right channel.
- To get a list of levels go to SITE_URL/levels.
- Then you can now submit your clears of level by using !clear lev-elc-ode
- You can also `!login` and submit your clears in the site
- You can submit a level by using `!add lev-elc-ode level name`
```

Machine Translated, with request for proper translation at the bottom maybe
```
!help ko 
-무엇이든하려면 오른쪽 채널에서 `!registe` r를 사용하여 먼저 등록해야합니다.
-레벨 목록을 보려면 SITE_URL/levels 로 이동하십시오.
-이제 `!clear lev-elc-ode` 를 사용하여 레벨 클리어를 제출할 수 있습니다
-당신은 또한`! login`을 할 수 있고 사이트에서 당신의 비운을 제출할 수 있습니다
-`!add lev-elc-ode level name` 을 사용하여 레벨을 제출할 수 있습니다.

번역이 틀렸다면 알려주십시오.
```
