### ISSUE TITLE
!judge in a pending reupload channel

### ISSUE THREAD

**Issue by a-unique-id** [TeamShellSMM/ShellBot3000#57]
**Describe the bug**
If you run !judge in a pending fixed level, or a pending not fixed level, it'll automatically assign it as a need fix again.

**To Reproduce**
1. Find/create a fixed reupload level
2. Create a channel for it under pending reupload catergory.
3. Run !judge
4. The channel will be deleted and the level change notification will announce that the level will requre a fix instead of approve or reject

**Expected behavior**
It should probably throw an error that indicates that we can't judge the level anymore

**Comment by Liafdev** [comment]
use of !judge has been prohibited in #60
