### ISSUE TITLE
!reupload approved level before pending votes

### ISSUE THREAD

**Issue by a-unique-id** [TeamShellSMM/ShellBot3000#58]
**Describe the bug**
A pending approved reupload level that was approved before approval votes was implemented wont be able to be fixapproved!

**To Reproduce**
1. Find a level before approval votes was implemented
2. Reupload the level. It's channel should appear in pending reupload category
3. Run !fixapprove
4. Will notify that there are not enough votes

**Expected behavior**
It should be re-approved

**Comment by Liafdev** [comment]
this is fixed in #60

**Comment by a-unique-id** [comment]
Pull request is merged and pushed to prod
