### ISSUE TITLE
Have an emoji label to discussion channels

### ISSUE THREAD

**Issue by a-unique-id** [TeamShellSMM/ShellBot3000#86]
**Is your feature request related to a problem? Please describe.**
With lots of channels, in the discord it might be difficult to identify levels with only one vote required, or levels that have not been actioned on for a while

**Describe the solution you'd like**
After experimenting we found that we can use emojis as part of a channel name. With this we could possibly use this to indicate the status of a level

Example:
- Levels that only need 1 more vote to judge
- Levels that have not been actioned in a while
- Levels that are made by first time makers

We also thought of putting number of approvals in the channel name but it might be too much/hides the level code

<img width="257" alt="image" src="https://user-images.githubusercontent.com/45527149/83506798-3b2ff780-a4fa-11ea-96e0-fe0b82557d76.png">

**Comment by Liafdev** [comment]
Also a label would be nice for unitiated makers on the discussion channels (same for the pending list). Might just be my opinion but I feel like giving those a bit more priority so they don't wait forever is the  way.
